### ISSUE TITLE
TypeError: _mliebelt_pgn_viewer_lib_pgnv__WEBPACK_IMPORTED_MODULE_4__.pgnView is not a function

### ISSUE THREAD

**Issue by olsbg** [mliebelt/pgn-parser#23]
Hi,

I am trying to use your package in Ionic/Angular project to read and parse chess PGN files but I cannot get it working.

`import * as PGNV from '@mliebelt/pgn-viewer/lib/pgnv';

PGNV.pgnView('board',{ pgn: '1. e4 e5 2. Nf3 Nc6 3. Bb5', pieceStyle: 'merida' });`

throws a following error:

core.js:4197 ERROR Error: Uncaught (in promise): TypeError: _mliebelt_pgn_viewer_lib_pgnv__WEBPACK_IMPORTED_MODULE_4__.pgnView is not a function
TypeError: _mliebelt_pgn_viewer_lib_pgnv__WEBPACK_IMPORTED_MODULE_4__.pgnView is not a function
    at new ReadpgnPage (readpgn.page.ts:127)
    at NodeInjectorFactory.ReadpgnPage_Factory [as factory] (ɵfac.js? [sm]:1)
    at getNodeInjectable (core.js:4029)
    at instantiateRootComponent (core.js:7826)
    at createRootComponent (core.js:18375)
    at ComponentFactory$1.create (core.js:22191)
    at ViewContainerRef.createComponent (core.js:10108)
    at IonRouterOutlet.activateWith (ionic-angular.js:2924)
    at ActivateRoutes.activateRoutes (router.js:2114)
    at router.js:2065
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27425)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)

@mliebelt I would appreciate your assistance.

Many thanks!

**Comment by olsbg** [comment]
Solved by:

- removing `import * as PGNV from '@mliebelt/pgn-viewer/lib/pgnv'; from TS module

- copying pgnv.js to src/assets

- adding "src/assets/js/pgnv.js" to "scripts" array in angular.json

**Comment by mliebelt** [comment]
Thank you for reporting this. I may not be able to improve the situation for you. However, the pgn-parser is a package in its own, so it should be possible to use it without the viewer. This should make it much easier to integrate.

I just looked it up, the `README.md` gives a complete example how to have the parser integrated in pure Javascript. That may be as well not possible for you, but the problem will be different. By having the parser only, you don't need any additional assets, so the package will be much smaller. Depending on what you want to do, this may be more appropriate.

But perhaps I misunderstood your context. The last line `PGNV.pgnView('board',{ pgn: '1. e4 e5 2. Nf3 Nc6 3. Bb5', pieceStyle: 'merida' });` seems to denote that you want to visualize the chess game in an HTML page.

Just for my understanding: I though Angular would be able to use new versions of Javascript, so the `import` command should be available?

**Comment by olsbg** [comment]
@mliebelt , many thanks for your reply. I wasn't able to implement it by using import but mentioned solution works.

Btw, do you have any suggestion on how to use parser.parse('[White "Me"] [Black "Magnus"] 1. f4 e5 2. g4 Qh4#', {startRule: "games"}) and return array of PGN strings without tags. Something like this:

{
	"games": [ {
		"tags": {
			"White": "Me",
			"Black": "Magnus"
		},
		"moves": {
			"turn": "w",
			"moveNumber": 1,
                        ...
		},
		"pgn": "1. f4 e5 2. g4 Qh4#"
	}
}

Many thanks for your support!

**Comment by mliebelt** [comment]
I just created a small test case, with your input and the following result (I leave out some of the entries in JSON).

    [
      {
        "tags": {
          "White": "Me",
          "Black": "Magnus"
        },
        "moves": [
          {
            "turn": "w",
            "moveNumber": 1,
            "notation": {...},
           ...
          },
          {
            "turn": "b",
            "moveNumber": null,
            "notation": {... },
           ...
          },
          {
            "turn": "w",
            "moveNumber": 2,
            "notation": {...},
            ...
          },
          {
            "turn": "b",
            "moveNumber": null,
            "notation": {...},
            ...
          }
        ]
      }
    ]

So what are differences:

* You get immediately an array of games (here with only one game)
* Moves is an array of move objects.
* There is no resulting pgn

The following code computes the pgn (without move numbers), just to show how to do it.

    let moves = res[0].moves
    let pgn = ''
    for (move of moves) {
       pgn += move.notation.notation
       pgn += ' '
    }

I hope this clarifies the topic.
