### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by MrBr** [mliebelt/pgn-parser#298]
Hey, I've started using the library and it saved me a lot of time.

Is there a way to donate?

Something symbolic, to buy a drink for the contributors.

**Comment by mliebelt** [comment]
Hey, you were the first one that asked! Great to get that feedback, I appreciate that a lot. That saved my day ...

If you want to support something chess-related, please do that for lichess. That is the greatest platform ever for playing chess, and I use their board named Chessground in my PgnViewerJS.

I don't think I will add the option to donate something to me, but I like your feedback. Just give me a star ;-)

**Comment by MrBr** [comment]
Also using Chessground and did donate to them, so got it covered :)

I see, in this case all I can say then is keep up with good job. Starred the repo.
