### ISSUE TITLE
Question: Use pgn-parser without node

### ISSUE THREAD

**Issue by JRamos29** [mliebelt/pgn-parser#30]
Hi @mliebelt. 

I need a parser for a stand-alone project and I have a question.

Since the pgn-parser doesn't have node dependencies, would be possible to run it without node? 
Like a simple js script, I mean. Or some functionality needs the node runtime?

Thanks in advance.

**Comment by mliebelt** [comment]
Yes, that is correct. There was even an interesting change done by another issue #22 

As a consequence, I changed the `README.md` to include that information. There is no functionality that needs the node runtime. The only dependency I have is the peg parser, but only at build time.

I hope that clarifies a little bit your topic.

**Comment by JRamos29** [comment]
Great. 
I've been searching for something like this, and this is the only one that parses the most part of the info that can there be within a pgn file, such as comments and variants as well. 

Congratulations on this excellent work.

**Comment by mliebelt** [comment]
So if you find any PGN that confirms to the standard, but cannot be read by the parser, please raise an issue.
