### ISSUE TITLE
Annotations in commentMove not in parse result?

### ISSUE THREAD

**Issue by tvanwalsum** [mliebelt/pgn-parser#383]
First of all, thanks for the great work!

When annotations (e.g. [%csl Ge4]) are in the comments that are interpreted as commentMove by the parser, those annotations do not appear output, but are stripped from the comments. 

E.g. when parsing the following pgn game: 

1.  e4 (d4)  { Test annotation [%cal Gd7d5] } e5

commentMove will become ' Test annotation ', and the annotations do not appear in the output format. Removing the variant (d4) will result in a commentDiag, which will have both the comment text and the annotations.

Am I doing something wrong, or are such annotations not supported?

Again, thanks for the nice software.

Best,
Theo

**Comment by mliebelt** [comment]
I am away from the computer, but I am sure those comments are part of the move. Look at https://github.com/mliebelt/pgn-parser/blob/main/test/test-pgn.ts, lines 152ff, the field is named commentDiag . You should find the structure in https://github.com/mliebelt/pgn-types/blob/main/src/types.ts

I hope that helps.

**Comment by mliebelt** [comment]
Reading the question again, now I understand it. The problem may be the order: move comment variant may work. looking at the grammar file (see link above) on line 272, the order must be that way. When I am back at the computer, I might add that to the grammar and make a new version then.

**Comment by tvanwalsum** [comment]
Thanks for your response. Don't know whether I fully understand, but I would be happy to try a new version. 

FYI, the issue is that some comments (e.g. those that are before a move, after a variant) become 'commentMove' in the move structure. In contrast to commentDiag (other comments), that contains a string with the comment, and possibly also colorArrows and colorFields, commentDiag itself is a string only.
E.g.:

"commentMove": "Test annotation.",

vs

"commentDiag": {
            "comment": " Test annotation.",
            "colorArrows": [
                "Gd5d7",
            ]
        }, 

even if commentMove contains annotations, such as in the example.

**Comment by mliebelt** [comment]
Have you tried to change the order and compare that? I can add later (in 10 days or so) add some test cases to reproduce your behavior. But in my opinion, order of move, then comment, then variants is more natural.

**Comment by tvanwalsum** [comment]
No, did not try yet. I use the npm version, first need to figure out how to run from an updated repos 😊. Will try that, will likely be somewhere next week. Will keep you updated. Thanks! 

Markus Liebelt ***@***.***> schreef op 22 juni 2023 21:38:19 CEST:

**Comment by tvanwalsum** [comment]
Did have a look at the grammar file, and would not know exactly what to change there; the order, I think, is already move comment variant?

I tried the following example:

> 'e4 (d4) { Test anno move [%csl Ge4] } e6 { Test anno diag [%csl Gd4] } Nf3 Nc6'

The two comments (before and after e6) both end up with move 'e6', which I think makes perfect sense (as it is after the variation d4). The corresponding JSON for move e6 is:
   {
      "moveNumber": null,
      "notation": {
        "fig": null,
        "strike": null,
        "col": "e",
        "row": "6",
        "check": null,
        "promotion": null,
        "notation": "e6"
      },
      "commentAfter": " Test anno diag",
      "commentMove": " Test anno move",
      "variations": [],
      "nag": null,
      "commentDiag": {
        "comment": " Test anno diag",
        "colorFields": [
          "Gd4"
        ]
      },
      "turn": "b"
    },

The problem is that commentMove is a string, and does not have the annotation anymore, nor does it store the annotation (Ge4) in other fields, such as is the case for commentDiag. 
The typescript also shows that commentMove is a string, whereas commentDiag is a GameComment (containing a string, colorArrows, colorFields). 

Changing line 276 in the grammar file from:

>       if (cm) { move.commentMove = cm.comment };

to

>       if (cm) { move.commentMove = cm };

seems to do the trick. Don't know whether that would have any side-effects, though.

**Comment by mliebelt** [comment]
Thank you a lot for the detailed example and explanation. There are numerous problems here:

* My code currently does not support comment annotations in the move comment. So if you want to have the comment annotation before you make the move, you have to ensure that the annotations are added to the move before. Then you have exactly the effect you want to have.
* If I follow your advise, I would have to have commentDiag twice in the same move, before the move and after the move. But there is only one field, which belong to the move itself. So when the move is done, then the circles and arrows are shown.
* There is one more special case that is supported: to have the commentDiag before the first move. This should be supported as well.

I would have to change some more than the grammar to support your case, and I think it is reasonable to have only one commentDiag per move.

The following pgn would give you the notation you want to have: `e4 { [%csl Ge4]  } (d4) { Test anno move } e6 { Test anno diag [%csl Gd4] } Nf3 Nc6`.

Therefore, I will close the ticket.

**Comment by tvanwalsum** [comment]
Thanks for the response (and for the very nice parser)!

As far as I see, the annotations are being parsed (they are in move comment, i.e. commentMove), but not stored in the resulting representation of the move. Instead of the above suggestion, I now added  in my local copy:

> 					move.commentPre = cm;

after the line were ca is assigned to move.commentDiag (so introducing a new field in the move.). This seems to work fine in my case, and updating it locally is fine.

You are right, it may not be clear how this should be used (i.e. two annotations in a move), will have to see how to deal with that. 

Best,
Theo

**Comment by mliebelt** [comment]
It was a decision I took some time ago, in using created PGN from Lichess, ChessTempo and others, and all of them do the graphical annotations (arrows, circles) in a comment after the move. Therefore the decision.

Bye
 Markus
