### ISSUE TITLE
`split` does not take additional newlines into account

### ISSUE THREAD

**Issue by theborakompanioni** [mliebelt/pgn-parser#462]
Lichess exports files containing a PGN with games separated by three newline chars (`\n`).
When using `split` this results in an array with "invalid" entries (see below).

Example Lichess output (from https://lichess.org/@/Lichess/download):
```pgn
[Event "Casual Correspondence game"]
[Site "https://lichess.org/JdVY5FQs"]
[Date "2016.06.17"]
[White "lichess AI level 3"]
[Black "pgn"]
[Result "1-0"]

1. d3 e5 2. e4 Ne7 3. d4 exd4 4. Nf3 Nbc6 5. Nxd4 Nxd4 6. Qxd4 d6 7. Qb4 Qd7 8. Qc4 g6 9. Qc3 1-0


[Event "Casual Correspondence game"]
[Site "https://lichess.org/yBF7F3et"]
[Date "2016.06.17"]
[White "pgn"]
[Black "lichess AI level 3"]
[Result "0-1"]

1. d4 d6 2. Nd2 e5 3. dxe5 Qe7 4. f4 f6 5. exf6 Qe3 6. fxg7 Bxg7 7. Nb3 Qb6 8. g3 Nf6 9. Bh3 Ne4 10. Bxc8 Qf2# 0-1
```

When using `split` the returned array contains 3 entries. Notice the second object only containing the tags (prefixed with the additional `\n`), the third only the moves.

```json
[
  {
    "tags": "[Event \\"Casual Correspondence game\\"]\\n[Site \\"https://lichess.org/JdVY5FQs\\"]\\n[Date \\"2016.06.17\\"]\\n[White \\"lichess AI level 3\\"]\\n[Black \\"pgn\\"]\\n[Result \\"1-0\\"]\\n[UTCDate \\"2016.06.17\\"]\\n[UTCTime \\"12:49:51\\"]\\n[WhiteElo \\"?\\"]\\n[BlackElo \\"1500\\"]\\n[Variant \\"Standard\\"]\\n[TimeControl \\"-\\"]\\n[ECO \\"C20\\"]\\n[Termination \\"Normal\\"]",
    "pgn": "1. d3 e5 2. e4 Ne7 3. d4 exd4 4. Nf3 Nbc6 5. Nxd4 Nxd4 6. Qxd4 d6 7. Qb4 Qd7 8. Qc4 g6 9. Qc3 1-0",
    "all": "[Event \\"Casual Correspondence game\\"]\\n[Site \\"https://lichess.org/JdVY5FQs\\"]\\n[Date \\"2016.06.17\\"]\\n[White \\"lichess AI level 3\\"]\\n[Black \\"pgn\\"]\\n[Result \\"1-0\\"]\\n[UTCDate \\"2016.06.17\\"]\\n[UTCTime \\"12:49:51\\"]\\n[WhiteElo \\"?\\"]\\n[BlackElo \\"1500\\"]\\n[Variant \\"Standard\\"]\\n[TimeControl \\"-\\"]\\n[ECO \\"C20\\"]\\n[Termination \\"Normal\\"]\\n\\n1. d3 e5 2. e4 Ne7 3. d4 exd4 4. Nf3 Nbc6 5. Nxd4 Nxd4 6. Qxd4 d6 7. Qb4 Qd7 8. Qc4 g6 9. Qc3 1-0"
  },
  {
    "tags": "",
    "pgn": "\\n[Event \\"Casual Correspondence game\\"]\\n[Site \\"https://lichess.org/yBF7F3et\\"]\\n[Date \\"2016.06.17\\"]\\n[White \\"pgn\\"]\\n[Black \\"lichess AI level 3\\"]\\n[Result \\"0-1\\"]\\n[UTCDate \\"2016.06.17\\"]\\n[UTCTime \\"12:48:52\\"]\\n[WhiteElo \\"1500\\"]\\n[BlackElo \\"?\\"]\\n[Variant \\"Standard\\"]\\n[TimeControl \\"-\\"]\\n[ECO \\"A41\\"]\\n[Termination \\"Normal\\"]",
    "all": "\\n[Event \\"Casual Correspondence game\\"]\\n[Site \\"https://lichess.org/yBF7F3et\\"]\\n[Date \\"2016.06.17\\"]\\n[White \\"pgn\\"]\\n[Black \\"lichess AI level 3\\"]\\n[Result \\"0-1\\"]\\n[UTCDate \\"2016.06.17\\"]\\n[UTCTime \\"12:48:52\\"]\\n[WhiteElo \\"1500\\"]\\n[BlackElo \\"?\\"]\\n[Variant \\"Standard\\"]\\n[TimeControl \\"-\\"]\\n[ECO \\"A41\\"]\\n[Termination \\"Normal\\"]"
  },
  {
    "tags": "",
    "pgn": "1. d4 d6 2. Nd2 e5 3. dxe5 Qe7 4. f4 f6 5. exf6 Qe3 6. fxg7 Bxg7 7. Nb3 Qb6 8. g3 Nf6 9. Bh3 Ne4 10. Bxc8 Qf2# 0-1",
    "all": "1. d4 d6 2. Nd2 e5 3. dxe5 Qe7 4. f4 f6 5. exf6 Qe3 6. fxg7 Bxg7 7. Nb3 Qb6 8. g3 Nf6 9. Bh3 Ne4 10. Bxc8 Qf2# 0-1"
  }
]
```

What do you think? Should one or more additional newlines be accounted for?
My personal feeling is, it would be better to do this here than asking all devs to call `split` with "normalized" strings (maybe even by adapting function `normalizeLineEndings`).

**Comment by mliebelt** [comment]
Sounds reasonable. Any idea how to fix that? It should of course be normalized, and the users (or generating software) should be free to add as many empty lines as they want, as long as the result is the same.

**Comment by theborakompanioni** [comment]
> Sounds reasonable. Any idea how to fix that? It should of course be normalized, and the users (or generating software) should be free to add as many empty lines as they want, as long as the result is the same.

Hey @mliebelt - thanks for you response. Maybe it is sufficient to just remove newline prefixes and ignore empty lines. I will try to address this in a PR, if that is okay for you, in the coming days (busy at the moment, but hope to have some free time on my hands next week). :pray:

**Comment by mliebelt** [comment]
I fixed the handling of newlines in the split function, and documented, that this only works in the ways that most files are exported. I have added a test case (from some of my lichess games) that demonstrates that the format used there can now be split. Hopefully your problem is solved then as well.

**Comment by theborakompanioni** [comment]
> I fixed the handling of newlines in the split function [...]

Works like a charm. Thank you :pray:
