### ISSUE TITLE
`parseGame` does not handle additional chars before move counter properly

### ISSUE THREAD

**Issue by theborakompanioni** [mliebelt/pgn-parser#463]
When parsing a PGN, it seems additional chars before the move counter are not handled properly.

Notice the `aa` before move `10`
```pgn
1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 d6 8. c3 O-O 9. h3 Nb8 aa10. d4 Nbd7
```

When given to `parseGame` it returns:
```js
...

    {
      "moveNumber": 9,
      "notation": {
        "fig": null,
        "strike": null,
        "col": "h",
        "row": "3",
        "check": null,
        "promotion": null,
        "notation": "h3"
      },
      "variations": [],
      "nag": null,
      "commentDiag": null,
      "turn": "w"
    },
    {
      "moveNumber": null,
      "notation": {
        "fig": "N",
        "strike": null,
        "col": "b",
        "row": "8",
        "check": null,
        "promotion": null,
        "notation": "Nb8"
      },
      "variations": [],
      "nag": null,
      "commentDiag": null,
      "turn": "b"
    },
    {
      "moveNumber": null,
      "notation": {
        "fig": null,
        "disc": "a",
        "strike": null,
        "col": "a",
        "row": "1",
        "check": null,
        "promotion": null,
        "notation": "aa1"
      },
      "variations": [],
      "nag": null,
      "commentDiag": null,
      "turn": "w"
    },
    {
      "moveNumber": 0,
      "notation": {
        "fig": null,
        "strike": null,
        "col": "d",
        "row": "4",
        "check": null,
        "promotion": null,
        "notation": "d4"
      },
      "variations": [],
      "nag": null,
      "commentDiag": null,
      "turn": "b"
    },
    {
      "moveNumber": null,
      "notation": {
        "fig": "N",
        "disc": "b",
        "strike": null,
        "col": "d",
        "row": "7",
        "check": null,
        "promotion": null,
        "notation": "Nbd7"
      },
      "variations": [],
      "nag": null,
      "commentDiag": null,
      "turn": "w"
    }
  ],
  "messages": []
}
```

**Comment by mliebelt** [comment]
Thank you for bringing that  to my attention, I will try to have a fix for that soon. Seems to be that the grammar is not strict enough. Btw, the move numbers will be ignored later on, so it is not so critical to have that ...

**Comment by mliebelt** [comment]
Checked it, and it seems some strange handling of 'aa' as a combination of discriminator? and column character (missing the row then??).  Seems to be more complicate than I thought.

**Comment by mliebelt** [comment]
Thinking twice, it seems just to be some legal notation, if you ignore the rules of chess, just take PGN as context. Let us see:

* You have some normal moves, and have just read `Nb8` (from black). 
* The next 3 characters are: `aa1`. The parser interprets:
  * a must be a discriminator, perhaps there are other options to go to a1.
  * a is then the target column, 1 the target row.

I have to think if there is some valid grammar rule, that ensures that combinations like that are then flagged as error. But hey, just typing anything in between legal notation may result in a legal move notation (not: move) ....

**Comment by mliebelt** [comment]
I have closed that issue, because I don't see any way to solve that _in the parser_. The parser has just a context free grammar, reading and interpreting the moves is done somewhere else. So no easy fix available.
