### ISSUE TITLE
Try out and measure alternative to peg.js

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/pgn-parser#50]
I saw recently the mentioning of http://chevrotain.io/docs/ as a blazing fast Javascript parser. When I looked at it, I saw different things that may be relevant or interesting:

* The speed seems to be much better. See [comparison of parsers](https://chevrotain.io/docs/features/blazing_fast.html) where peg.js is at ~20% of the speed.
* After having mastered the possibilities of peg.js, the setup of Chevrotain is completely different. So the learning curve is not so easy.
* There are 2 aspects that may hinder:
  * There is no compilation, and the initial setup of the parser may be long. It is unclear if that initial setup is measured as well in the speed comparison above. This would kill what I want to do with it (parsing most of the time only one or a few games, where current ~10.000 games is parsed in 3 seconds).
  * There is the demand to tell the parser how big the lookahead is. Is that possible at all? And will that influence the speed?

So if I ever will check that, the following should be done:

1. Define the part of the grammar that should be build with Chevrotain. A good candidate would be a (simplified) parsing of the moves only. The rest could be ignored. To measure it, big databases of games should be used.
2. Build the grammar, but set a limit how much time can be spent. I have not the time to spend weeks to have a small part of the parser built.
3. Define how to measure it then. Differentiate the setup of the parser (once done), and the speed of the parser itself.
4. Report the results.

**Comment by MichaelLeeHobbs** [comment]
You know the spec is not so complex. Could write a parser by hand. I've written an HL7 parser by hand. The spec there is less complex in some ways as the structure is very ridged.

**Comment by mliebelt** [comment]
At hindsight, the parser is fast enough by any measure. It is for parsing in the frontend (mostly), and if someone needs some more percent, do it! Therefore I close that ticket, because I will never work on it (as long as peggy is maintained and works).
