### ISSUE TITLE
pgn-parser fails on PGN holding Lichess Puzzles

### ISSUE THREAD

**Issue by Bebul** [mliebelt/pgn-parser#51]
While working on `PgnViewerJS` ticket [Guess the move](https://github.com/mliebelt/PgnViewerJS/issues/2) I was now forced to edit the PGN generated by https://github.com/linrock/chess-puzzle-maker , because it contains tags not listed in `pgn-parser`.

```
[PuzzleCategory "Material"]
[PuzzleEngine "Stockfish 13"]
[PuzzleMakerVersion "0.5"]
[PuzzleWinner "White"]
```

I get long error with list of what tags were **Expected** but `P` was found. When I deleted these four tags, my `pgnPuzzle` worked as expected, so only these tags are the culprits.

**Note1:** it was not problem version in 3rd march 2021, when I forked first
**Note2:** I have noticed you work on bunch of things and I can live with these tags deleted for now, so there is **_no big priority_**. But, I would like to get pgn-parser not throwing exception when these four tags are present.

Thanks a lot for your work, nice to cooperate.

**Comment by mliebelt** [comment]
Thanks for noting this. I was aware that this is a change, but thought that will nave (nearly) no impact. But there may be more additional tags generated by others, so I have to adjust the grammar.

The reason I did this was that I wanted to have rules applied where the structure of the tags was known. But a wrong value may lead to the catch-all rule, where everything is accepted.

I will see if I can find a fix patch for it, without throwing away the validation of values that should be well structured.

**Comment by mliebelt** [comment]
Fix was easier than I thought, will generate a new version for it.
