### ISSUE TITLE
cannot parse chessjs generated pgn

### ISSUE THREAD

**Issue by Mansour-J** [mliebelt/pgn-parser#528]
I generated a PGN from `chess.js` by giving it moves and calling `chess.pgn()` - and now try to parse it and recieeve below errors:

![image](https://github.com/mliebelt/pgn-parser/assets/12991664/adcacfb2-70e2-4ee7-b37e-2b5e87fe3ce6)

```
[Event "Fork"]
[SetUp "1"]
[FEN "4r2k/R7/5N1p/p7/5p2/1P5P/P4PPK/2r5 b - - 5 44"]
[Chapter "From: 500 To: 600"]
[Informational "False"]

44. ... Rf8 45. Rh7#
```

I have tried to load this pgn in Lichess and few other websites and they are all fine. Is there something wrong with this pgn based on the PGN spec? or it's the parser?

**Comment by mliebelt** [comment]
If you look at the [PGN specification](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#822-movetext-move-number-indications), it says:

> ... PGN import format move number indications may have zero or more period characters following the digit sequence that gives the move number; one or more white space characters may appear between the digit sequence and the period(s). ...

That means the following:

* You may have as first move `44.........      Rf8`, no error.
* Or you may have as first move `44    .....   Rf8`, no error.

The problem lays in the 2 times `.` character with spaces in between. I will think of if the grammar could be changed, to be more flexible here, but it conforms to the  specification (which is not known too much ...).

Thank you for the information!

**Comment by mliebelt** [comment]
@Mansour-J  I released a new patch version of pgn-parser, that fixes the bug you mentioned. Could you please check that the new version works with the examples you provided?

**Comment by Mansour-J** [comment]
Sorry I was away in weekend - yes it is fixed - below is a screenshot of the stuff variations I tried with it ~ Thanks 🙌🙏

![image](https://github.com/mliebelt/pgn-parser/assets/12991664/dcb4c9eb-a595-4cf1-924d-5cd8dc3bdbf4)
