### ISSUE TITLE
doesn't handle Chess.com crazy house pgn's

### ISSUE THREAD

**Issue by seanwessmith** [mliebelt/pgn-parser#54]
fails on @ symbol in crazyhosue pgns

for example: 12... B@e7 {[%clk 0:00:45.6]}

**Comment by mliebelt** [comment]
@seanwessmith  Thank you a lot for creating that issue. I will have a look at it this weekend, a fix should be easy. What do you think would be an appropriate flag here? The current json is

![image](https://user-images.githubusercontent.com/520039/116664581-f9713080-a998-11eb-8c8b-54a0d4a9b14c.png)

From [Wikipedia](https://en.wikipedia.org/wiki/Crazyhouse), the result should be expanded by:

`{ ..., drop: true, ... }`

The rest can be as it is.

**Comment by mliebelt** [comment]
I did  the change to the grammar, added one test case (and fixed the wrong time format, at least due to the specification), and published a new version 1.2.8 to NPM. You should be able to use that version, to read the games then.
