### ISSUE TITLE
Throws on valid Tag pair [Event "Let\\'s Play!"]

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [mliebelt/pgn-parser#72]
Doesn't like the \\ I think is both a bug in pgn-parser and Chess.com export. From my understanding of pgn spec http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1 the tag should be valid. At the same time Chess.com export adding the \\ is likely a side effect of how they convert the game object too text.

Edit: sample - https://www.chess.com/game/daily/336811359

**Comment by mliebelt** [comment]
Ok, I could reproduce the bug. The tag is valid, but it is most of the time a bad idea to combine quotes, backslashes, ... in a string. I will make the grammar much simpler here, by allowing anything inside the tag value, with the exception of the doublequote.
