### ISSUE TITLE
Parsing Issues

### ISSUE THREAD

**Issue by Philipp-Sc** [mliebelt/pgn-parser#91]
Hi,

I just installed the new version and tested it. I got the following error:

`chess-meta.js:23 TypeError: I.a.parse is not a function`

It points to 

`var pgn = parser.parse(text, {startRule: "games"})`

With any of the previous versions I do not run into this error. (The error happens in both cases with %depth and without.)
Any idea?

Best regards,
Philipp

**Comment by mliebelt** [comment]
Perhaps I did something wrong in packaging, normally it is sufficient to do the build step before publishing it. I have no idea, so I have to take some time in the evening to address that.

Sorry for the inconvenience ...

Could you tell how you do the import? Do you have a reference to the sources?

**Comment by mliebelt** [comment]
Found the "error". Because we have now 2 objects exported (parser, splitter), your import should look like this:

`import { parser } from "@mliebelt/pgn-parser";`

instead of the previous

`import parser from "@mliebelt/pgn-parser";`

**Comment by Philipp-Sc** [comment]
Hi Markus,

thank you for updating the readme. You were right, I was using the wrong import statement.
Now everything works perfectly!

Best regards,
Philipp
